# Generated by Django 3.2.21 on 2023-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticdemo',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
