# Generated by Django 3.2.21 on 2023-09-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
