services:
  backend:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    env_file:
      - .env
    volumes:
      - .:/app

  postgres_db:
    image: postgres
    restart: always
    # command: -p 5434
    env_file:
      - .env
    # expose:
    #   - 5434
    ports:
      - "5434:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
#   backend_data:
