# Generated by Django 3.2.21 on 2023-09-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
