services:
  backend:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:


