"""empty message

Revision ID: adffeb7a4e7e
Revises: dc75060d8f9b
Create Date: 2023-09-27 02:30:09.770049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adffeb7a4e7e'
down_revision = 'dc75060d8f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_post', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_post', type_='unique')

    # ### end Alembic commands ###
